//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamCost
    {
        public int id { get; set; }
        public Nullable<int> Cost { get; set; }
        public Nullable<int> IdBook { get; set; }
    
        public virtual Exam01 Exam01 { get; set; }
    }
}
